(defun c:dclloader()
  (setq dlg_file (getfiled "选择要预览的对话框所在文件" "D:\\牛炜奇的文件\\cad材料\\" "DCL" 2))
  (if (= dlg_file nil) (exit))
  (setq dlg_name (getstring "\n对话框名称:"))
  (if (= dlg_name "") (exit))
  (setq dlg_id (load_dialog dlg_file))
  (if (< dlg_id 0) (exit))
  (setq std 0)
  (if (not (new_dialog dlg_name dlg_id)) (exit))
  (action_tile "accept" "(done_dialog 1)")
  (action_tile "cancel" "(done_dialog 0)")
  (setq std (start_dialog))
  (unload_dialog dlg_id)
  (cond ((= std 1) (princ "确定"))
	((= std 0) (princ "取消"))
	)
  (princ)
)